# Amazon S3 Configuration
development: 
  s3_bucket: medectomy
  s3_key: AKIAIRD463QJ4GJ5V3HQ
  s3_secret: 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

  content_directory: <%= "#{Rails.root}/content/*" %>

# Amazon S3 Configuration
production: 
  s3_bucket: medectomy
  s3_key: AKIAIRD463QJ4GJ5V3HQ
  s3_secret: 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

  content_directory: <%= "#{Rails.root}/content/*" %>