graylog_server_version: "0.20.0-rc.1-1"
graylog_server_prefix: "/usr/local"
graylog_server_dir: "#{graylog_server_prefix}/graylog2-server-#{graylog_server_version}"
graylog_server_pid_file: "/var/run/graylog-server.pid"
graylog_server_port: 12201
graylog_server_syslog_port: 12514

graylog_web_version: "0.20.0-rc.1-1"
graylog_web_prefix: "/usr/local"
graylog_web_dir: "#{graylog_web_prefix}/graylog2-web-interface-#{graylog_web_version}"
graylog_web_pid_file: "/var/run/graylog-web.pid"
graylog_web_port: 9000

graylog_web_username: admin
graylog_web_password: admin1

graylog_mongo_database: graylog2
graylog_elasticsearch_index: "graylog2_#{Rubber.env}"

web_tools_proxies:
  graylog:
    role: graylog_web
    port: "#{graylog_web_port}"
    path: /

role_dependencies:
  graylog_server: [graylog_mongodb, graylog_elasticsearch]
  graylog_mongodb: [mongodb]
  graylog_elasticsearch: [elasticsearch]

roles:
  graylog_server:
    packages: [openjdk-7-jdk, mongodb-10gen]
  graylog_web:
    packages: [openjdk-7-jdk]

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_server_secret: e19d05876f085db2beae0b835f31fd54013f2dc6175ebbabd800428ffe752625fae19b8654572004c8ef46bbc210b81d3d3d741f7bc554c5101a8bb425d209d3eba2c7beb8cd45e097c6987062c6cc48ba2080a7bb3777db51ba197c0ff4b237

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_web_secret: ae7e1cd4295667b249612aa06a8ab7cac4660eee1f415ce7b011b66feda59b303f7c1065539da4dcd528cfc5d5a3fd7a0266ebe28206206393b3a93d3f52039fe85082a919fb94e38ca2006480a5dbd0db53a3564a932a5b6ad2f32d0208551d
